services:
  web:
    build: .
    ports:
      - 80:5000
    volumes:
      - .:/app
    command: flask --app back run --debug --host=0.0.0.0
  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app