services:
  app:
    build: .
    ports:
      - 8080:5000
    volumes:
      - ./app:/app
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      APP_SECRET_KEY: ''
      API_URL: ''
    entrypoint: ["/entrypoint.sh"]
    networks:
      - filmy_network

networks:
  filmy_network:
    name: filmy_network