services:
  web:
    build: .
    ports:
      - 81:5000
    volumes:
      - ./front:/app
    command: flask --app app run --debug --host=0.0.0.0
  backend:
    build: .
    ports:
      - 5000:5000
    command: flask --app app run --debug --host=0.0.0.0
    volumes:
      - ./back:/app