FROM python:3.13

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY ./ ./

RUN pip install -r requirements.txt

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - &&\
apt-get install -y nodejs

WORKDIR /app/app
RUN npm install && \
    npm run build

CMD ["flask", "run", "--debug", "--host=0.0.0.0"]